sudo: required
services:
        - docker
before_install:
        - docker build -t ducvu2810/docker-react  -f Dockerfile.dev .
script:
        - docker run -e CI=true  ducvu2810/docker-react npm run test 
